[package]
name = "sample-enclave"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
aws-nitro-enclaves-nsm-api = "0.4.0"
base64 = "0.22"
serde = "1.0"
serde_json = "1.0"
vsock = "0.5.1"